### ISSUE TITLE
Problems compiling... undefined symbol: libusb_clear_halt (maybe it's not compiled the right way?)

### ISSUE THREAD

**Issue by ThiagoNicolielo** [bensondaled/pseyepy#1]
Hi!,

I am using Ubuntu 16.04
and Python 3.6.1 with anaconda environment
```
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
```

I know that's problematic and as each machine/environment/configurations are different, so, sometimes it is very difficult to solve individual problems, but I had several problems trying to compile ***and using / importing*** pseyepy.

* Problems with g++
which I solved linking /usr/bin/clang++-libc++ to /usr/bin/g++
```
ln -s /usr/bin/g++ /usr/bin/clang++-libc++
```
and
inserting this code (at line 1938 of **/usr/include/c++/v1/string**):
```
#if _LIBCPP_STD_VER <= 14
        _NOEXCEPT_(is_nothrow_move_constructible<allocator_type>::value)
#else
        _NOEXCEPT
#endif
```

* Problems with libusb:
I tried many things, the last action that ***basically solved it*** was to copy my /lib/x86_64-linux-gnu/libusb-1.0.so.0 to /usr/lib/libusb-1.0.so

* And problems with cameras.pyx that wasn't been included,
so, I edited ***pseyepy/__init__.py*** inserting these lines before python imports :
```
import pyximport
pyximport.install()
```

* But I still have trouble, when I try to do, @ python:
```
from pseyepy import cameras
```
I get:

> import pseyepy
from pseyepy import cameras
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: /home/thiago/anaconda3/envs/envSpyderPython3.6/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6-linux-x86_64.egg/pseyepy/cameras.cpython-36m-x86_64-linux-gnu.so: undefined symbol: libusb_clear_halt

Have any sugestions?

Thanks in advance and anyway, for your kindness sharing your work!

**Comment by bensondaled** [comment]
This strikes me on first glance as a libusb version issue. I know that functions have been removed or changed in different versions, though it does appear you're using 1.0... maybe this is a specific platform-dependent difference, as I'm on macOS. 

Libusb does appear to implement libusb_clear_halt (http://libusb.sourceforge.net/api-1.0/group__dev.html#ga5b321176ce7f18cfec369dd3ab7d431e), so maybe it's worth trying a fresh download and re-install of libusb?

Happy to hear you're trying to get this going!

**Comment by bensondaled** [comment]
You may want to try installing again. I've redone how the package installs, just forcing it to compile and link to a fresh version of libusb, so it might work (though haven't tested on linux)

**Comment by christophergeek** [comment]
@ThiagoNicolielo did you ever fix this issue? I'm getting the same problem

**Comment by bensondaled** [comment]
I still haven't managed to replicate it on my own setup. Are you on Ubuntu as well? And did you use the libusb that I packaged with the repo? If you did, maybe try linking to a separate dedicated libusb? I suspect right now that it's an inconsistency between libusb versions across the OS's

**Comment by christophergeek** [comment]
Thanks for your reply. I was using the libusb in the repo yeah.

I managed to get it working by adding `'udev'` to the `libs` variable in _setup.py_ (got from here: https://stackoverflow.com/questions/12140859/import-hid-in-python-results-in-error-hid-so-undefined-symbol-libusb-open). I think I also had to remove the two `-stdlib=libc++` flags in _setup.py_ to get the compilation to finish.

**Comment by bensondaled** [comment]
Great, thanks!
