### ISSUE TITLE
warning: unused variable 'newCam' (@ file ps3eye_capi.cpp)

### ISSUE THREAD

**Issue by ThiagoNicolielo** [bensondaled/pseyepy#2]
I don't know if this is a problem, but @ compile time g++ says that ***in file ps3eye_capi.cpp***, the variable newCam is not being used.

g++ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipseyepy/src -I/usr/include/libusb-1.0 -I/home/thiago/anaconda3/envs/envSpyderPython3.6/include/python3.6m -c pseyepy/src/ps3eye_capi.cpp -o build/temp.linux-x86_64-3.6/pseyepy/src/ps3eye_capi.o -std=c++11 -stdlib=libc++
***pseyepy/src/ps3eye_capi.cpp:138:15: warning: unused variable 'newCam' [-Wunused-variable]***
    ps3eye_t *newCam = new ps3eye_t(id, ps3eye_context->devices[id], width, height, fps, outputFormat); // is stored in open...

**Comment by bensondaled** [comment]
This has no consequence, but is rather just an extraneous variable I added at some point for readability. Can be ignored safely
